version: '3.1'
services:
  nginx:
    container_name: mdp_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    container_name: mdp_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    extra_hosts:
      - host.docker.internal:host-gateway